name: Static Apps
markdown: redcarpet
pygments: true
exclude:
  - Gemfile
  - divshot.json
  - .bowerrc
  - .travis.yml
  - Gemfile.lock
  - bower.json
  - divshot.json
  - README.md
assets:
  js_compressor: uglifier
  sources:
    - _assets/images
    - _assets/stylesheets
    - _assets/javascripts
    - _bower
